name = "my-linkedin-profile-clone"
compatibility_date = "2025-09-15"
main = "./functions/_worker.js"
pages_build_output_dir = "./dist/client"

[site]
bucket = "./dist/client"

[build]
command = "bun run build"
