#!/usr/bin/env bun
/**
 * Post-build: flatten `<dir>/index.html` → `<dir>.html` so a static host
 * (Cloudflare Pages) serves every route at its slash-free URL directly (200)
 * instead of 301/308-redirecting `/about` → `/about/`. Then generate the
 * reverse trailing-slash redirects (`/about/` → `/about`, 301).
 *
 * Runs after `vite build` (see package.json). Works with `bun run` or `tsx`.
 */
import fs from "node:fs";
import path from "node:path";

const BUILD_DIR = path.join(process.cwd(), "dist/client");
const SKIP_DIRS = new Set(["assets"]); // real asset dirs, never routes

interface FlattenedRoute {
  path: string;
}
const flattenedRoutes: FlattenedRoute[] = [];

/** Recursively flatten <dir>/index.html → <dir>.html (children before parents). */
function flattenDirectory(dir: string, baseDir: string = BUILD_DIR): void {
  if (!fs.existsSync(dir) || !fs.statSync(dir).isDirectory()) return;

  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    if (SKIP_DIRS.has(entry.name)) continue;

    const fullPath = path.join(dir, entry.name);
    flattenDirectory(fullPath, baseDir); // recurse first

    const indexPath = path.join(fullPath, "index.html");
    if (fs.existsSync(indexPath)) {
      if (fullPath === baseDir) continue; // never flatten the root index.html

      // dist/client/about/index.html → dist/client/about.html
      fs.copyFileSync(indexPath, fullPath + ".html");

      const routePath = "/" + path.relative(baseDir, fullPath).replace(/\\/g, "/");
      flattenedRoutes.push({ path: routePath });

      fs.unlinkSync(indexPath);
      if (fs.readdirSync(fullPath).length === 0) fs.rmdirSync(fullPath);
    }
  }
}

/** Reverse trailing-slash redirects: /about/ → /about (301). Longest paths first. */
function generateRedirects(): string {
  const sorted = [...flattenedRoutes].sort((a, b) => b.path.length - a.path.length);
  const lines = sorted.map(
    r => `${(r.path + "/").padEnd(35)} ${r.path.padEnd(30)} 301`
  );
  return [
    "# AUTO-GENERATED by scripts/flatten-html.ts",
    "# Reverse trailing-slash redirects for the flattened (slash-free) HTML.",
    "# DO NOT EDIT MANUALLY — regenerated on every build.",
    "",
    lines.join("\n"),
    "",
  ].join("\n");
}

/** Write dist/client/_redirects (prepending any hand-written public/_redirects). */
function writeRedirects(content: string): void {
  const out = path.join(BUILD_DIR, "_redirects");
  const publicRedirects = path.join(process.cwd(), "public/_redirects");
  const existing = fs.existsSync(publicRedirects)
    ? fs.readFileSync(publicRedirects, "utf-8").trim()
    : "";
  fs.writeFileSync(out, existing ? `${existing}\n\n${content}` : content);
  console.log(`✓ Generated ${flattenedRoutes.length} redirect rules → ${out}`);
}

function main(): void {
  if (!fs.existsSync(BUILD_DIR)) {
    console.error(`Build directory not found: ${BUILD_DIR}`);
    process.exit(1);
  }
  flattenDirectory(BUILD_DIR);
  console.log(`✓ Flattened ${flattenedRoutes.length} routes to slash-free .html`);
  writeRedirects(generateRedirects());
  console.log("✓ HTML flattening complete");
}

main();
